print("Hola 'holaaa' Mundo")
print("Esta es una linea \nEsta es otra linea")
print("\tEsta es la tercera linea")
print("This isn't a number")
print("Este signo \\ es una barra invertida")
input("Dime tu nombre: ")
print((input("Dime tu nombre: ")))
print((input("¿Qué estás estudiando?")))
print(input("Escribe tu nombre: ")+" "+(input("Escribe tu apellido: ")))
print((input("Escribe tu nombre:"))+" "+(input("Escribe tu apellido:")))