print("fede"+"hola")
print("me llamo 'federico'")
print("Esta es una Linea\nY esta es otra linea")
print("\tEsta es la tercera linea")
print('This isn\'t a number')
print("Esta es una \\ barra invertida")
print("Linea 1\nLinea 2\nLinea 3")
print("A\tB\tC\nD\tE\tF\nG\tH\tI")
print("Barra Normal: /\nBarra Invertida: \\")