cant_ahorr=float(input('Ingresar el valor Ahorrado: '))
inter=float(4/100)
ren_primer=round(float(cant_ahorr+(cant_ahorr*inter)),2)
ren_seg=round(float(ren_primer+(ren_primer*inter)),2)
ren_ter=round(float(ren_seg+(ren_seg*inter)),2)
ren_cuarto=round(float(ren_ter+(ren_ter*inter)),2)   
print('Cantidad Ahorrada: ', cant_ahorr)
print('rendimientos: Primer Año: ', ren_primer)
print('rendimientos: Segundo Año: ', ren_seg)
print('rendimientos: Tercer Año: ', ren_ter)
print('rendimientos: Cuarto Año: ', ren_cuarto)
