print("-------------")
print("Ejercicio2: PROMEDIO")
print("-------------")
print("Ingrese las Notas")
n1 = float(input("Nota 1: "))
n2 = float(input("Nota 2: "))
n3 = float(input("Nota 3: "))
P = int((n1+n2+n3)/3)
print(P)
