print("-----------------")
print("Ejercicio1: CALCULAR DISTANCIA")
print("-----------------")
print("Ingrese la velocidad y el tiempo de la unidad movil")
V = float(input("Velocidad: "))
T = int(input("Tiempo:"))
D = int(V * T)
print(D)
